# Lab 2: numpy

#### Practice Exercise 1

Create the following NumPy arrays:
1. A 1-D array called zeros having 10 elements and all the elements are set to zero.
2. A 1-D array called vowels having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’.
3. A 2-D array called ones having 2 rows and 5 columns and all the elements are set to 1 and dtype as int.
4. Use nested Python lists to create a 2-D array called myarray1 having 3 rows and 3 columns and store the following data: 2.7,  0,  -2,  3.4,  10.6,  0,  -19 99.9 13
5. A 2-D array called myarray2 using arange() having 3 rows and 5 columns with start value = 4, step size 4 and dtype as float


In [4]:
import numpy as np

# Create a 1-D array of zeros
zeros = np.zeros(10)
print("Zeros array:")
print(zeros)

# Create a 1-D array of vowels
vowels = np.array(['a', 'e', 'i', 'o', 'u'])
print("\nVowels array:")
print(vowels)

# Create a 2-D array of ones
ones = np.ones((2, 5), dtype=int)
print("\nOnes array:")
print(ones)

# Create a 2-D array using nested lists
myarray1 = np.array([[2.7, 0, -2], [3.4, 10.6, 0], [-19, 99.9, 13]])
print("\n2-D array myarray1:")
print(myarray1)

# Create a 2-D array using arange() that starts at 4, with a step size of 4
myarray2 = np.arange(4, 64, 4, dtype=float).reshape(3, 5)
print("\n2-D array myarray2:")
print(myarray2)


Zeros array:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Vowels array:
['a' 'e' 'i' 'o' 'u']

Ones array:
[[1 1 1 1 1]
 [1 1 1 1 1]]

2-D array myarray1:
[[  2.7   0.   -2. ]
 [  3.4  10.6   0. ]
 [-19.   99.9  13. ]]

2-D array myarray2:
[[ 4.  8. 12. 16. 20.]
 [24. 28. 32. 36. 40.]
 [44. 48. 52. 56. 60.]]


# New section

In [5]:
import numpy as np

# Assume the arrays have been created as previously discussed:
zeros = np.zeros(10)
vowels = np.array(['a', 'e', 'i', 'o', 'u'])
ones = np.ones((2, 5), dtype=int)
myarray1 = np.array([[2.7, 0, -2], [3.4, 10.6, 0], [-19, 99.9, 13]])
myarray2 = np.arange(4, 64, 4, dtype=float).reshape(3, 5)

# Information about the arrays
print("Information about the arrays:")
print("Zeros - dimensions:", zeros.ndim, "shape:", zeros.shape, "size:", zeros.size, "dtype:", zeros.dtype, "itemsize:", zeros.itemsize)
print("Vowels - dimensions:", vowels.ndim, "shape:", vowels.shape, "size:", vowels.size, "dtype:", vowels.dtype, "itemsize:", vowels.itemsize)
print("Ones - dimensions:", ones.ndim, "shape:", ones.shape, "size:", ones.size, "dtype:", ones.dtype, "itemsize:", ones.itemsize)
print("Myarray1 - dimensions:", myarray1.ndim, "shape:", myarray1.shape, "size:", myarray1.size, "dtype:", myarray1.dtype, "itemsize:", myarray1.itemsize)
print("Myarray2 - dimensions:", myarray2.ndim, "shape:", myarray2.shape, "size:", myarray2.size, "dtype:", myarray2.dtype, "itemsize:", myarray2.itemsize)

# Reshape the array 'ones' to have all elements in a single row
reshaped_ones = ones.reshape(1, 10)
print("\nReshaped Ones array:")
print(reshaped_ones)

# Display the 2nd and 3rd element of the array 'vowels'
print("\n2nd and 3rd element of vowels:", vowels[1:3])

# Display all elements in the 2nd and 3rd row of 'myarray1'
print("\n2nd and 3rd row of myarray1:")
print(myarray1[1:3])

# Display the elements in the 1st and 2nd column of 'myarray1'
print("\n1st and 2nd column of myarray1:")
print(myarray1[:, 0:2])

# Display the elements in the 1st column of the 2nd and 3rd row of 'myarray1'
print("\n1st column of the 2nd and 3rd row of myarray1:")
print(myarray1[1:3, 0])

# Reverse the array 'vowels'
reversed_vowels = vowels[::-1]
print("\nReversed Vowels array:")
print(reversed_vowels)





Information about the arrays:
Zeros - dimensions: 1 shape: (10,) size: 10 dtype: float64 itemsize: 8
Vowels - dimensions: 1 shape: (5,) size: 5 dtype: <U1 itemsize: 4
Ones - dimensions: 2 shape: (2, 5) size: 10 dtype: int64 itemsize: 8
Myarray1 - dimensions: 2 shape: (3, 3) size: 9 dtype: float64 itemsize: 8
Myarray2 - dimensions: 2 shape: (3, 5) size: 15 dtype: float64 itemsize: 8

Reshaped Ones array:
[[1 1 1 1 1 1 1 1 1 1]]

2nd and 3rd element of vowels: ['e' 'i']

2nd and 3rd row of myarray1:
[[  3.4  10.6   0. ]
 [-19.   99.9  13. ]]

1st and 2nd column of myarray1:
[[  2.7   0. ]
 [  3.4  10.6]
 [-19.   99.9]]

1st column of the 2nd and 3rd row of myarray1:
[  3.4 -19. ]

Reversed Vowels array:
['u' 'o' 'i' 'e' 'a']


Using the arrays created in Question above, write NumPy commands for the following:
1. Find the dimensions, shape, size, data type of the items and itemsize of arrays zeros, vowels, ones, myarray1 and myarray2.
2. Reshape the array ones to have all the 10 elements in a single row.
3. Display the 2nd and 3rd element of the array vowels.
4. Display all elements in the 2nd and 3rd row of the array myarray1.
5. Display the elements in the 1st and 2nd column of the array myarray1.
6. Display the elements in the 1st column of the 2nd and 3rd row of the array myarray1.
7. Reverse the array of vowels.

In [6]:
#Write your answer here

import numpy as np

# Assume the arrays have been created as previously discussed:
zeros = np.zeros(10)
vowels = np.array(['a', 'e', 'i', 'o', 'u'])
ones = np.ones((2, 5), dtype=int)
myarray1 = np.array([[2.7, 0, -2], [3.4, 10.6, 0], [-19, 99.9, 13]])
myarray2 = np.arange(4, 64, 4, dtype=float).reshape(3, 5)

# Display array properties
arrays = [zeros, vowels, ones, myarray1, myarray2]
for arr in arrays:
    print(f"Array: {arr}\nDimensions: {arr.ndim}, Shape: {arr.shape}, Size: {arr.size}, Dtype: {arr.dtype}, Itemsize: {arr.itemsize}\n")

# Reshape ones
ones_reshaped = ones.reshape(1, 10)
print("Reshaped Ones:", ones_reshaped)

# Elements of vowels
print("Vowels elements:", vowels[1:3])

# Elements of myarray1 (rows and columns)
print("Rows 2 and 3 of myarray1:", myarray1[1:3])
print("Columns 1 and 2 of myarray1:", myarray1[:, :2])
print("Column 1, Rows 2 and 3 of myarray1:", myarray1[1:3, 0])

# Reverse vowels
print("Reversed vowels:", vowels[::-1])


Array: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Dimensions: 1, Shape: (10,), Size: 10, Dtype: float64, Itemsize: 8

Array: ['a' 'e' 'i' 'o' 'u']
Dimensions: 1, Shape: (5,), Size: 5, Dtype: <U1, Itemsize: 4

Array: [[1 1 1 1 1]
 [1 1 1 1 1]]
Dimensions: 2, Shape: (2, 5), Size: 10, Dtype: int64, Itemsize: 8

Array: [[  2.7   0.   -2. ]
 [  3.4  10.6   0. ]
 [-19.   99.9  13. ]]
Dimensions: 2, Shape: (3, 3), Size: 9, Dtype: float64, Itemsize: 8

Array: [[ 4.  8. 12. 16. 20.]
 [24. 28. 32. 36. 40.]
 [44. 48. 52. 56. 60.]]
Dimensions: 2, Shape: (3, 5), Size: 15, Dtype: float64, Itemsize: 8

Reshaped Ones: [[1 1 1 1 1 1 1 1 1 1]]
Vowels elements: ['e' 'i']
Rows 2 and 3 of myarray1: [[  3.4  10.6   0. ]
 [-19.   99.9  13. ]]
Columns 1 and 2 of myarray1: [[  2.7   0. ]
 [  3.4  10.6]
 [-19.   99.9]]
Column 1, Rows 2 and 3 of myarray1: [  3.4 -19. ]
Reversed vowels: ['u' 'o' 'i' 'e' 'a']


Using the arrays created in Question above, write NumPy commands for the following:
1. Divide all elements of array ones by 3.
2. Add the arrays myarray1 and myarray2.
3. Subtract myarray1 from myarray2 and store the result in a new array.
4. Multiply myarray1 and myarray2 elementwise.
5. Do the matrix multiplication of myarray1 and myarray2 and store the result in a new array myarray3.
6. Divide myarray1 by myarray2.
7. Find the cube of all elements of myarray1 and divide the resulting array by 2.
8. Find the square root of all elements of myarray2   and divide the resulting array by 2. The result  should be rounded to two places of decimals.

In [8]:
import numpy as np

# Define the arrays
myarray1 = np.array([[2.7, 0, -2], [3.4, 10.6, 0], [-19, 99.9, 13]])
myarray2 = np.arange(4, 64, 4, dtype=float).reshape(3, 5)

# Corrected matrix multiplication:
# We can only use a portion of myarray2 that makes the inner dimensions match.
# For example, use the first three columns of myarray2
myarray2_portion = myarray2[:, :3]
myarray3 = np.dot(myarray1, myarray2_portion.T)  # Now myarray2_portion.T is 3x3

print("Result of matrix multiplication (myarray3):")
print(myarray3)


Result of matrix multiplication (myarray3):
[[-1.3200e+01  8.0000e-01  1.4800e+01]
 [ 9.8400e+01  3.7840e+02  6.5840e+02]
 [ 8.7920e+02  2.7572e+03  4.6352e+03]]


Using the arrays created above, write NumPy commands for the following:
1. Find the transpose of ones and myarray2.
2. Sort the array vowels in reverse.
3. Sort the array myarray1 such that it brings the lowest value of the column in the first row and so on.

In [9]:
# Write your answer here

import numpy as np

# Assume the arrays have been created as previously discussed:
ones = np.ones((2, 5), dtype=int)
myarray2 = np.arange(4, 64, 4, dtype=float).reshape(3, 5)
vowels = np.array(['a', 'e', 'i', 'o', 'u'])
myarray1 = np.array([[2.7, 0, -2], [3.4, 10.6, 0], [-19, 99.9, 13]])

# Transpose of arrays ones and myarray2
transpose_ones = ones.T
transpose_myarray2 = myarray2.T

# Sort the array vowels in reverse
sorted_vowels_reverse = np.sort(vowels)[::-1]

# Sort array myarray1 on columns (ascending)
sorted_myarray1 = np.sort(myarray1, axis=0)

print("Transpose of ones:")
print(transpose_ones)

print("Transpose of myarray2:")
print(transpose_myarray2)

print("Vowels sorted in reverse:")
print(sorted_vowels_reverse)

print("myarray1 sorted by columns (lowest value in the first row):")
print(sorted_myarray1)



Transpose of ones:
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
Transpose of myarray2:
[[ 4. 24. 44.]
 [ 8. 28. 48.]
 [12. 32. 52.]
 [16. 36. 56.]
 [20. 40. 60.]]
Vowels sorted in reverse:
['u' 'o' 'i' 'e' 'a']
myarray1 sorted by columns (lowest value in the first row):
[[-19.    0.   -2. ]
 [  2.7  10.6   0. ]
 [  3.4  99.9  13. ]]


Create a 2-D array called myarray4 using arange() having 14 rows and 3 columns with start value = -1, step size 0.25 having. Split this array row wise into 3 equal parts and print the result.

In [10]:
# Write your answer here
import numpy as np

# Calculate the stop value for np.arange
start_value = -1
step_size = 0.25
num_elements = 14 * 3  # because we need 14 rows of 3 columns
stop_value = start_value + step_size * num_elements

# Create the 2-D array myarray4
myarray4 = np.arange(start_value, stop_value, step_size).reshape(14, 3)

# Split the array row-wise into 3 equal parts
split_arrays = np.array_split(myarray4, 3)

# Print each of the resulting parts
for index, part in enumerate(split_arrays):
    print(f"Part {index + 1}:")
    print(part)
    print()  # For better readability between parts




Part 1:
[[-1.   -0.75 -0.5 ]
 [-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]
 [ 1.25  1.5   1.75]
 [ 2.    2.25  2.5 ]]

Part 2:
[[2.75 3.   3.25]
 [3.5  3.75 4.  ]
 [4.25 4.5  4.75]
 [5.   5.25 5.5 ]
 [5.75 6.   6.25]]

Part 3:
[[6.5  6.75 7.  ]
 [7.25 7.5  7.75]
 [8.   8.25 8.5 ]
 [8.75 9.   9.25]]



Using the myarray4 created in the above questions, write commands for the following:
1. Find the sum of all elements.
2. Find the sum of all elements row wise
3. Find the sum of all elements column wise.
4. Find the max of all elements.
5. Find the min of all elements in each row.
6. Find the mean of all elements in each row.
7. Find the standard deviation column wise.

In [13]:
#import numpy as np

# Define the arrays
start_value = -1
step_size = 0.25
num_elements = 14 * 3  # because we need 14 rows of 3 columns
stop_value = start_value + step_size * num_elements
myarray4 = np.arange(start_value, stop_value, step_size).reshape(14, 3)

# Calculate various statistics
total_sum = np.sum(myarray4)
row_sum = np.sum(myarray4, axis=1)
column_sum = np.sum(myarray4, axis=0)
max_value = np.max(myarray4)
row_min = np.min(myarray4, axis=1)
row_mean = np.mean(myarray4, axis=1)
column_std = np.std(myarray4, axis=0)

# Printing the results
print("Sum of all elements:", total_sum)
print("Sum of all elements row-wise:", row_sum)
print("Sum of all elements column-wise:", column_sum)
print("Max of all elements:", max_value)
print("Min of all elements in each row:", row_min)
print("Mean of all elements in each row:", row_mean)
print("Standard deviation column-wise:", column_std)




Sum of all elements: 173.25
Sum of all elements row-wise: [-2.25  0.    2.25  4.5   6.75  9.   11.25 13.5  15.75 18.   20.25 22.5
 24.75 27.  ]
Sum of all elements column-wise: [54.25 57.75 61.25]
Max of all elements: 9.25
Min of all elements in each row: [-1.   -0.25  0.5   1.25  2.    2.75  3.5   4.25  5.    5.75  6.5   7.25
  8.    8.75]
Mean of all elements in each row: [-0.75  0.    0.75  1.5   2.25  3.    3.75  4.5   5.25  6.    6.75  7.5
  8.25  9.  ]
Standard deviation column-wise: [3.02334666 3.02334666 3.02334666]


#### Practice Exercise 2
Read the coordinates of the capital cities of the world from the country-capital-lat-long-population.csv file. Use NumPy to print the name and coordinates of the capital city closest to the Saudi Arabia capital - Riyadh.

Note that:

1. The Country Name for Saudi Arabia is given as Saudi Arabia in the data.
2. The ‘closeness’ of capital cities from the Saudi Arabia capital is based on the Euclidean distance of their coordinates to those of the Saudi Arabia capital.


Hints:

1. Use read_html() from the Pandas library to read the table.
2. Use the to_numpy() function of the Pandas DataFrame class to convert a DataFrame to a Numpy array
3. Use broadcasting to compute the euclidean distance of capital cities from Riyadh.

In [19]:
import os
print(os.getcwd())
file_path = 'country-capital-lat-long-population.csv'  # Direct filename if in the same directory
data = pd.read_csv(file_path)

import pandas as pd
import numpy as np
import os

# Check the current working directory to understand where the file should be located
print("Current working directory:", os.getcwd())

# Specify the file path (update this with the actual path or use just the filename if in the same directory)
file_path = 'country-capital-lat-long-population.csv'

# Try to load the data
try:
    data = pd.read_csv(file_path)
    print("File loaded successfully!")

    # Extract the relevant columns and convert to a NumPy array
    capitals = data[['CountryName', 'CapitalName', 'CapitalLatitude', 'CapitalLongitude']].to_numpy()

    # Find Riyadh's coordinates in the array
    riyadh_coords = capitals[capitals[:, 1] == 'Riyadh', 2:].astype(float)

    # Calculate Euclidean distances from Riyadh to all other capitals
    distances = np.sqrt(np.sum((capitals[:, 2:].astype(float) - riyadh_coords) ** 2, axis=1))

    # Find the index of the minimum distance
    closest_index = np.argmin(distances)

    # Print the name and coordinates of the closest capital city
    closest_city = capitals[closest_index]
    print(f"The closest capital city to Riyadh is {closest_city[1]} in {closest_city[0]}, Coordinates: Lat {closest_city[2]}, Long {closest_city[3]}")

except FileNotFoundError:
    print(f"FileNotFoundError: No such file or directory: '{file_path}' - Please check the file path and try again.")
except Exception as e:
    print(f"An error occurred: {e}")



/content
Current working directory: /content
File loaded successfully!
An error occurred: "None of [Index(['CountryName', 'CapitalName', 'CapitalLatitude', 'CapitalLongitude'], dtype='object')] are in the [columns]"


#### Practical Exercise 2

Use NumPy to:

1. Print the names of the countries of the top 10 capital cities closest to the US capital - Washington DC.

2. Create and print a NumPy array containing the coordinates of the top 10 cities.

In [26]:
import pandas as pd
import numpy as np

# Load the data
file_path = 'country-capital-lat-long-population.csv'
data = pd.read_csv(file_path)

# Extract the relevant columns and convert to a NumPy array
# Use the correct column names from your dataset
capitals = data[['Country', 'Capital City', 'Latitude', 'Longitude']].to_numpy()

# Coordinates of Washington D.C.
washington_dc_coords = np.array([38.9072, -77.0369])

# Calculate Euclidean distances to Washington D.C.
distances = np.sqrt(np.sum((capitals[:, 2:].astype(float) - washington_dc_coords) ** 2, axis=1))

# Get indices of the 10 closest capitals
closest_indices = np.argsort(distances)[:10]

# Print the names of the countries of the top 10 closest capitals
closest_countries = capitals[closest_indices, 0]
print("\nTop 10 closest countries to Washington D.C. are:")
print(closest_countries)

# Create and print a NumPy array containing the coordinates of the top 10 cities
top_10_coordinates = capitals[closest_indices, 2:].astype(float)
print("\nCoordinates of the top 10 closest capital cities:")
print(top_10_coordinates)





Top 10 closest countries to Washington D.C. are:
['United States of America' 'Canada' 'Bahamas' 'Bermuda' 'Cuba'
 'Turks and Caicos Islands' 'Cayman Islands' 'Haiti' 'Jamaica'
 'Dominican Republic']

Coordinates of the top 10 closest capital cities:
[[ 38.8951 -77.0364]
 [ 45.4166 -75.698 ]
 [ 25.0582 -77.3431]
 [ 32.2915 -64.778 ]
 [ 23.1195 -82.3785]
 [ 21.4612 -71.1419]
 [ 19.2866 -81.3744]
 [ 18.5392 -72.335 ]
 [ 17.997  -76.7936]
 [ 18.4896 -69.9018]]
